### ISSUE TITLE
Creating new COVID-19 Survey

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#219]
New COVID-19 Survey: ready for programming

DCEG document: https://nih.app.box.com/file/1147390260827
IMS document: https://nih.app.box.com/file/1147555236167

**Comment by cusackjm** [comment]
Please note new edits:
[COVIDINTRO] Added sentence to intro text
[COV9] Added text to question text
[COV23B8A] Deleted question 
[COV23B8B] Deleted question
[COV24A14] Deleted question
[COV28] Added response

**Comment by cusackjm** [comment]
Questions added to DD and Question Types Document on 2/23/2023

**Comment by boyd-mj** [comment]
This survey has been coded and we are awaiting the updated JSON to test the converted markup. @cusackjm if there are content changes since 3/9, please point us toward those and we will make them. Thanks.

**Comment by cusackjm** [comment]
Updated COV27 response variable to _v2r0 in the questionnaire documents

**Comment by woodruffr** [comment]
@cusackjm COVID-19 Survey is ready to deliver. However, as per our ongoing weekly conversation, we accepted Gene's request to change the versioning. It is changed in the Data Dictionary and Mark-up, back to V1, but not in the Questionnaire:

![image](https://github.com/episphere/questionnaire/assets/81166095/0b70eb20-e7cb-4664-83ac-c27a62d87a73)

**Comment by cusackjm** [comment]
I changed COV27_MY and COV3_MY back to _v1r0 in the questionnaire documents

**Comment by cusackjm** [comment]
confirmed fixed in dev testing 7/24/2023

**Comment by cusackjm** [comment]
Decision to change COV27, COV27_MY, COV3 and COV3_MY to _v2r0 in questionnaire documents and DD

@boyd-mj does this require markdown edits/redelivery?

**Comment by woodruffr** [comment]
Yes, this will require a mark-up change, new JSON, and redelivery. The screenshots below show the current mark-up. Note the variable names that the transformer software uses to link the concept IDs to the mark-up. What is in the JSON must match what is in the mark-up.

![image](https://github.com/episphere/questionnaire/assets/81166095/33e30d5e-aa85-41fe-8f89-967e77f19aeb)

![image](https://github.com/episphere/questionnaire/assets/81166095/d481598d-8d40-4269-8de9-36a974e82927)

**Comment by woodruffr** [comment]
Do you want us to make these changes? Has Gene worked out how to have the versioning different between the Source Qustion Name and the Variable Name and still get the JSON to create correctly?

**Comment by cusackjm** [comment]
I updated the DD and questionnaire document. Gene is OOO so will have to wait for him to generate JSON on Mon 7/31. This should not be an issue, as the source question and question text variable names are the same

**Comment by cusackjm** [comment]
No issues identified in Dev testing on 11/1/2023. 
Next step: stage testing & back-end data testing

**Comment by KELSEYDOWLING7** [comment]
@cusackjm  Everything looks good on the backend!
